import React, {useState} from 'react';
import {useDraftState,useFormTask} from './ui';
const labels={style_name:'款式名称',sku_code:'货号',color_info:'颜色',size_range:'尺码',fabric_details:'面料',accessory_details:'辅料',craftsmanship:'制作工艺',material_info:'物料说明'};
export function DemandDetails({demand,quantity}){
 if(!demand)return <p className="muted">历史订单未提供详细需求。</p>;
 const p=demand.planning_context||{},r=demand.production_requirements||{};
 return <><dl className="demand-details"><div><dt>品类 / 分配数量</dt><dd>{p.category||'未提供'} · {quantity} 件/双</dd></div><div><dt>总需求 / 目标交期</dt><dd>{p.quantity} 件/双 · {p.deadline_days} 天</dd></div><div><dt>合作方式</dt><dd>{r.cooperation_mode||'未提供'}</dd></div>{Object.entries(labels).map(([key,label])=><div key={key}><dt>{label}</dt><dd>{demand.bom_data?.[key]||'未提供'}</dd></div>)}<div><dt>备注</dt><dd>{r.special_notes||'未提供'}</dd></div></dl><div className="photo-grid">{(demand.sample_images||[]).map((src,i)=><a key={i} href={src} target="_blank" rel="noreferrer"><img src={src} alt={`需求样品 ${i+1}`}/></a>)}</div></>;
}
function capacity(f,days){return Math.max(0,(f.dailyCapacity||0)*Math.min(days||10,10)-(f.analytics?.booked||0));}
export function AllocationModal({proposal,data,onSubmit,onClose,Modal,accountId}){
 const actor=accountId||localStorage.getItem('shoe-session-v1');
 const key=actor+':allocation:'+(proposal.reassignOrderId||proposal.requestId||'current');
 const demand=proposal.demand,total=proposal.quantity??demand.planning_context.quantity;
 const [selected,setSelected]=useDraftState(key+':selected',()=>proposal.candidates?.length?{[proposal.candidates[0].factory_id]:total}:{});
 const [requestId]=useDraftState(key+':requestId',()=>proposal.requestId || (proposal.reassignOrderId ? 'reassign-'+proposal.reassignOrderId : crypto.randomUUID()));
 const [confirm,setConfirm]=useDraftState(key+':confirm',false),[ack,setAck]=useDraftState(key+':ack',false),[showAll,setShowAll]=useDraftState(key+':showAll',!proposal.candidates?.length);
 const {busy,error,run}=useFormTask(key,onClose,{kind:'allocation',accountId:actor,proposal:{...proposal,requestId}});
 const candidates=proposal.candidates||[],candidateIds=candidates.map(c=>c.factory_id);
 const factories=[...candidates.map(c=>data.factories.find(f=>f.id===c.factory_id)).filter(Boolean),...data.factories.filter(f=>!candidateIds.includes(f.id))];
 const sum=Object.values(selected).reduce((n,x)=>n+Number(x||0),0),allocations=Object.entries(selected).map(([factory_id,quantity])=>({factory_id,quantity:Number(quantity)}));
 const valid=allocations.length>0&&allocations.every(a=>Number.isSafeInteger(a.quantity)&&a.quantity>0)&&sum===total;
 function toggle(id){setSelected(current=>{if(id in current){const next={...current};delete next[id];return next;}if(!demand.planning_context.splittable)return {[id]:total};return {...current,[id]:Object.keys(current).length?Math.max(0,total-sum):total};});setAck(false);}
 function submit(){if(!valid||!ack)return;run(()=>onSubmit({requestId,title:demand.bom_data.style_name||demand.bom_data.sku_code,demand,allocations,...(proposal.reassignOrderId?{reassignOrderId:proposal.reassignOrderId}:{})}));}
 return <Modal title={confirm?'确认提交合作需求':proposal.reassignOrderId?'重新分配被拒绝数量':'选择工厂并分配数量'} onClose={onClose}><form onSubmit={e=>{e.preventDefault();if(busy)return;if(confirm)submit();else if(valid)setConfirm(true);}}><p className="muted">{demand.bom_data.style_name} · 本次分配 {total} 件/双 · 目标交期 {demand.planning_context.deadline_days} 天</p>{!confirm?<><p className="allocation-notice">{proposal.notice||'推荐仅供参考，报价、工艺和排期待工厂确认。'}{!demand.planning_context.splittable&&' 本需求不允许拆单。'}</p><div className="candidate-list">{factories.filter(f=>showAll||candidateIds.includes(f.id)).map(f=>{const c=candidates.find(c=>c.factory_id===f.id),chosen=f.id in selected,available=capacity(f,demand.planning_context.deadline_days);return <article key={f.id} className={`candidate-card ${chosen?'chosen':''}`}><label className="candidate-select"><input disabled={busy} type="checkbox" checked={chosen} onChange={()=>toggle(f.id)}/><strong>{f.name}</strong><span>{c?'相关候选':'手动选择 · 匹配未确认'}</span></label><p>{(f.categories||[]).join(' · ')||'尚未登记品类'}</p>{c&&<><ul>{c.reasons.map((r,i)=><li key={i}>{r}</li>)}</ul>{c.semantic_note&&<p>{c.semantic_note}</p>}<small>资料中明确登记的需求工艺：{c.confirmed_processes.join('、')||'暂无完全对应项'}</small><small>待确认工艺：{c.unconfirmed_processes.join('、')||'具体样品及质量要求仍需确认'}</small></>}<div className="candidate-facts">MOQ {f.min_order_quantity} · 交期内已知可用产能 {available}</div>{c?.risks?.map((r,i)=><p className="candidate-risk" key={i}>{r}</p>)}{chosen&&<label className="field">分配给 {f.name} 的数量<input disabled={busy} aria-label={`分配数量 ${f.name}`} type="number" min="1" max={total} step="1" value={selected[f.id]} onChange={e=>{setSelected(s=>({...s,[f.id]:e.target.value}));setAck(false);}}/></label>}{chosen&&(Number(selected[f.id])<f.min_order_quantity||Number(selected[f.id])>available)&&<p className="candidate-risk">当前数量存在 MOQ / 产能风险，提交后需工厂确认。</p>}</article>;})}</div>{!showAll&&<button type="button" className="text-button" onClick={()=>setShowAll(true)}>查看全部工厂 / 手动选择</button>}<div className="allocation-total">已分配 <b>{sum}</b> / {total} 件/双 {sum!==total&&<span> · 请调整至总数一致</span>}</div></>:<><ul className="confirmation-list">{allocations.map(a=>{const f=data.factories.find(f=>f.id===a.factory_id);return <li key={a.factory_id}><strong>{f.name} · {a.quantity} 件/双</strong><p>最小起订量 {f.min_order_quantity}，已知可用产能 {capacity(f,demand.planning_context.deadline_days)}。工艺、物料、报价和排期待确认。</p></li>;})}</ul><label className="risk-ack"><input disabled={busy} type="checkbox" checked={ack} onChange={e=>setAck(e.target.checked)}/>我已了解推荐和产能风险，本次提交为待工厂确认的需求。</label></>}{error&&<p className="form-error" role="alert">{error}</p>}<div className="modal-actions"><button type="button" className="secondary" disabled={busy} onClick={()=>confirm?setConfirm(false):onClose()}>{confirm?'返回调整':'取消'}</button>{confirm?<button type="submit" className="primary" disabled={busy||!ack}>{busy?'提交中…':'提交给所选工厂'}</button>:<button type="submit" className="primary" disabled={!valid}>核对分配与风险</button>}</div></form></Modal>;
}
export function OrderDetailsModal({order,data,account,mutate,notify,onClose,Modal,actions}){
 const key=(account?.id||'guest')+':order:'+order.id;
 const [action,setAction]=useDraftState(key+':action',''),[reason,setReason]=useDraftState(key+':reason',''),[ack,setAck]=useDraftState(key+':ack',false);
 const {busy,error,run,setError}=useFormTask(key,onClose,{kind:'order',accountId:account?.id,orderId:order.id});
 const factory=data.factories.find(f=>f.id===order.factoryId),p=order.demand?.planning_context;
 const available=capacity(factory,p?.deadline_days),risk=order.quantity<factory.min_order_quantity||order.quantity>available;
 const canAct=account?.id===order.factoryId&&order.status==='pending';
 function change(status){run(async()=>{await mutate('order-status',{orderId:order.id,status,reason,confirmRisks:ack});notify(status==='production'?'已接单，产能已更新':'已拒绝，品牌方可查看原因并重新分配');});}
 return <Modal title="订单需求详情" onClose={onClose}><form onSubmit={e=>{e.preventDefault();if(!busy&&canAct&&action&&(action==='accept'?ack:reason.trim()))change(action==='accept'?'production':'rejected');}}><p>{order.title} · {order.quantity} 件/双</p><p className="muted">品牌：{data.brands.find(b=>b.id===order.brandId)?.name} · 工厂：{factory.name}</p><DemandDetails demand={order.demand} quantity={order.quantity}/>{order.risks?.length>0&&<div className="order-risks"><h3>提交时的推荐风险</h3><ul>{order.risks.map((r,i)=><li key={i}>{r}</li>)}</ul></div>}{order.rejectionReason&&<p className="form-error">拒绝原因：{order.rejectionReason}</p>}{order.reassignedBy&&<p className="muted">该部分数量已重新分配，原拒绝记录保留。</p>}{canAct&&<><p>当前最小起订量 {factory.min_order_quantity} · 交期内已知可用产能 {available}</p>{action==='accept'&&<label className="risk-ack"><input disabled={busy} type="checkbox" checked={ack} onChange={e=>setAck(e.target.checked)}/>{risk?'已知存在 MOQ / 产能风险，我确认可协调资源承接此单。':'我已核对需求、报价及排期，确认承接此单。'}</label>}{action==='reject'&&<label className="field">拒绝原因<textarea disabled={busy} required maxLength={500} rows={3} value={reason} onChange={e=>setReason(e.target.value)} placeholder="请说明工艺、交期或其他无法承接的原因"/></label>}{error&&<p className="form-error" role="alert">{error}</p>}<div className="modal-actions">{!action?<><button type="button" className="secondary" onClick={()=>setAction('reject')}>拒绝接单</button><button type="button" className="primary" onClick={()=>setAction('accept')}>确认接单</button></>:<><button type="button" className="secondary" disabled={busy} onClick={()=>{setAction('');setError('');}}>返回</button><button type="button" className="primary" disabled={busy||(action==='accept'?!ack:!reason.trim())} onClick={()=>change(action==='accept'?'production':'rejected')}>{busy?'处理中…':action==='accept'?'确认承接并占用产能':'提交拒绝原因'}</button></>}</div></>}</form>{actions}</Modal>;
}
